### ISSUE TITLE
Docker运行报错了

### ISSUE THREAD

**Issue by wj2008** [tickstep/aliyunpan#219]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xadef7a]
goroutine 59 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc0000f62a0, 0xdde098, 0xc0001b6a00, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:101 +0x1dfa
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc0000f62a0, 0xdde098, 0xc0001b6a00, 0xc0001aa1c0, 0xc0002e83c0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x30d
using existed sync_drive_config.json file

**Comment by wj2008** [comment]
bug复现是在v0.2.5
v0.2.4 暂时没啥问题

**Comment by xiaoyaofenfen** [comment]
看这log是记录功能有问题，你关闭记录功能试试，改这个ALIYUNPAN_SYNC_LOG=false
```
version: '3'
services:
  sync:
    image: tickstep/aliyunpan-sync:<tag>
    container_name: aliyunpan-sync
    ...
    environment:
      - ALIYUNPAN_SYNC_LOG=false

```
