### ISSUE TITLE
Token登录失败

### ISSUE THREAD

**Issue by HuggingAha** [tickstep/aliyunpan#31]
Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": lookup auth.aliyundrive.com on [::1]:53: read udp [::1]:39272->[::1]:53: read: connection refused

请问怎么解决？

**Comment by tickstep** [comment]
这个想网络问题

**Comment by baloyou** [comment]
在ubuntu上以docker-compose模式运行，我确认token的正确性，以及ubuntu能正常上网（我内网的另一台电脑，能够正常链接网络和访问网页云盘）

```
aliyunpan-sync | 登录失败
aliyunpan-sync |   名称                   值               建议值               描述
aliyunpan-sync |   cache_size             0B               1KB ~ 256KB          下载缓存, 如果硬盘占用高或下载速度慢, 请尝试调大此值
aliyunpan-sync |   max_download_parallel  0                1 ~ 20               最大下载并发量，即同时下载文件最大数量
aliyunpan-sync |   max_upload_parallel    0                1 ~ 20               最大上传并发量，即同时上传文件最大数量
aliyunpan-sync |   max_download_rate      不限制                                限制单个文件最大下载速度, 0代表不限制
aliyunpan-sync |   max_upload_rate        不限制                                限制单个文件最大上传速度, 0代表不限制
aliyunpan-sync |   transfer_url_type      1                1-默认，2-阿里云ECS  上传下载URL类别。除非在阿里云ECS（暂只支持经典网络）服务器中使用，不然请设置1
aliyunpan-sync |   savedir                /root/Downloads                       下载文件的储存目录
aliyunpan-sync |   proxy                                                        设置代理, 支持 http/socks5 代理，例如：http://127.0.0.1:8888
aliyunpan-sync |   local_addrs                                                  设置本地网卡地址, 多个地址用逗号隔开，例如：127.0.0.1,192.168.100.126
aliyunpan-sync |
aliyunpan-sync | 保存配置成功!
aliyunpan-sync |
aliyunpan-sync | 未登录账号
aliyunpan-sync | using existed sync_drive_config.json file
aliyunpan-sync | 未登录账号
aliyunpan-sync | login use refresh token: b2f2*******5612
aliyunpan-sync | Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
aliyunpan-sync | 登录失败
aliyunpan-sync |   名称                   值               建议值               描述
aliyunpan-sync |   cache_size             0B               1KB ~ 256KB          下载缓存, 如果硬盘占用高或下载速度慢, 请尝试调大此值
aliyunpan-sync |   max_download_parallel  0                1 ~ 20               最大下载并发量，即同时下载文件最大数量
aliyunpan-sync |   max_upload_parallel    0                1 ~ 20               最大上传并发量，即同时上传文件最大数量
aliyunpan-sync |   max_download_rate      不限制                                限制单个文件最大下载速度, 0代表不限制
aliyunpan-sync |   max_upload_rate        不限制                                限制单个文件最大上传速度, 0代表不限制
aliyunpan-sync |   transfer_url_type      1                1-默认，2-阿里云ECS  上传下载URL类别。除非在阿里云ECS（暂只支持经典网络）服务器中使用，不然请设置1
aliyunpan-sync |   savedir                /root/Downloads                       下载文件的储存目录
aliyunpan-sync |   proxy                                                        设置代理, 支持 http/socks5 代理，例如：http://127.0.0.1:8888
aliyunpan-sync |   local_addrs                                                  设置本地网卡地址, 多个地址用逗号隔开，例如：127.0.0.1,192.168.100.126
aliyunpan-sync |
aliyunpan-sync | 保存配置成功!
aliyunpan-sync |
aliyunpan-sync | 未登录账号
```

使用docker-compose 运行的备份模式，下面是配置文件

```
version: '3'
services:
  sync:
    image: tickstep/aliyunpan-sync:v0.1.8
    container_name: aliyunpan-sync
    restart: always
    volumes:
      # 指定本地备份目录绝对路径：/tickstep/Documents/设计文档
      - /usbdata/test:/home/app/data:rw
      # （可选）可以指定JS插件sync_handler.js用于过滤文件，详见下面的插件说明
      #- ./plugin/js/sync_handler.js:/home/app/config/plugin/js/sync_handler.js
      # （推荐）挂载sync_drive同步数据库到本地，这样即使容器销毁，同步数据库还可以用于以后使用
      - /opt/docker/aliyunpan_sync_drive:/home/app/config/sync_drive
    environment:
      - TZ=Asia/Shanghai
      # refresh token
      - ALIYUNPAN_REFRESH_TOKEN=b2f2**********61a5612
      # 上传下载链接类型：1-默认 2-阿里ECS环境
      - ALIYUNPAN_TRANSFER_URL_TYPE=1
      # 下载文件并发数
      - ALIYUNPAN_DOWNLOAD_PARALLEL=2
      # 上传文件并发数
      - ALIYUNPAN_UPLOAD_PARALLEL=2
      # 下载数据块大小，单位为KB，默认为10240KB，建议范围1024KB~10240KB
      - ALIYUNPAN_DOWNLOAD_BLOCK_SIZE=1024
      # 上传数据块大小，单位为KB，默认为10240KB，建议范围1024KB~10240KB
      - ALIYUNPAN_UPLOAD_BLOCK_SIZE=10240
      # 指定网盘文件夹作为备份目录，不要指定根目录
      - ALIYUNPAN_PAN_DIR=/备份盘/
      # 备份模式：upload(备份本地文件到云盘), download(备份云盘文件到本地), sync(双向同步备份)
      - ALIYUNPAN_SYNC_MODE=upload
```
