### ISSUE TITLE
CPU占用百分百？

### ISSUE THREAD

**Issue by Aliang-code** [tickstep/aliyunpan#473]
![图片](https://github.com/user-attachments/assets/e035d5cc-259d-42c6-87b0-57610aeda5a8)
![图片](https://github.com/user-attachments/assets/c49addb7-2e72-42a7-84ec-407d01961be2)

```
aliyunpan-sync:
    image: tickstep/aliyunpan-sync:v0.3.4
    container_name: aliyunpan-sync
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - /data/nextcloud/root/files/:/home/app/data/nextcloud/aliang
      - /data/nextcloud/bianca/files/:/home/app/data/nextcloud/bianca
      - /data/aliyunpan/sync_drive:/home/app/config/sync_drive
      - /data/aliyunpan/aliyunpan_config.json:/home/app/config/aliyunpan_config.json
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - ALIYUNPAN_DOWNLOAD_PARALLEL=3
      - ALIYUNPAN_UPLOAD_PARALLEL=3
      - ALIYUNPAN_DOWNLOAD_BLOCK_SIZE=10240
      - ALIYUNPAN_UPLOAD_BLOCK_SIZE=10240
      - ALIYUNPAN_PAN_DIR=/nas
      - ALIYUNPAN_SYNC_MODE=upload
      - ALIYUNPAN_SYNC_POLICY=exclusive
      - ALIYUNPAN_SYNC_CYCLE=infinity
      - ALIYUNPAN_SYNC_DRIVE=backup
      - ALIYUNPAN_SYNC_LOG=true
      - ALIYUNPAN_LOCAL_DELAY_TIME=3   
```
